import {
  Service,
  Incident,
  BusinessCapability,
  DependencyNode,
  DependencyEdge,
  TelemetrySource,
} from './types';

export const services: Service[] = [
  {
    id: 'api-gateway',
    name: 'API Gateway',
    status: 'healthy',
    description: 'Central API gateway handling all external traffic',
    team: 'Platform',
    tier: 'T1',
    businessOwner: 'Sarah Chen',
    slaTarget: 99.99,
    slaCurrent: 99.97,
    errorRate: 0.03,
    latencyP50: 12,
    latencyP99: 89,
    throughput: 45200,
    dependencies: ['auth-service', 'user-service', 'order-service', 'payment-service'],
    clients: ['web-app', 'mobile-app', 'partner-api'],
    revenueImpact: 2400000,
    activeIncidents: 0,
    sparklineData: [45, 48, 42, 50, 47, 45, 52, 48, 44, 46, 50, 48],
  },
  {
    id: 'auth-service',
    name: 'Authentication Service',
    status: 'healthy',
    description: 'Handles user authentication and token management',
    team: 'Identity',
    tier: 'T1',
    businessOwner: 'Marcus Johnson',
    slaTarget: 99.99,
    slaCurrent: 99.99,
    errorRate: 0.01,
    latencyP50: 8,
    latencyP99: 45,
    throughput: 32100,
    dependencies: ['user-db', 'redis-cache', 'identity-provider'],
    clients: ['api-gateway'],
    revenueImpact: 2400000,
    activeIncidents: 0,
    sparklineData: [32, 34, 31, 33, 35, 32, 34, 36, 33, 31, 34, 32],
  },
  {
    id: 'order-service',
    name: 'Order Service',
    status: 'degraded',
    description: 'Core order processing and management',
    team: 'Commerce',
    tier: 'T1',
    businessOwner: 'Lisa Park',
    slaTarget: 99.95,
    slaCurrent: 99.82,
    errorRate: 0.18,
    latencyP50: 45,
    latencyP99: 320,
    throughput: 8900,
    dependencies: ['order-db', 'payment-service', 'inventory-service', 'notification-service'],
    clients: ['api-gateway'],
    revenueImpact: 1800000,
    activeIncidents: 1,
    sparklineData: [89, 92, 88, 95, 120, 145, 180, 210, 195, 165, 140, 125],
  },
  {
    id: 'payment-service',
    name: 'Payment Service',
    status: 'healthy',
    description: 'Payment processing and transaction management',
    team: 'Finance Tech',
    tier: 'T1',
    businessOwner: 'David Kim',
    slaTarget: 99.99,
    slaCurrent: 99.98,
    errorRate: 0.02,
    latencyP50: 120,
    latencyP99: 450,
    throughput: 3200,
    dependencies: ['payment-db', 'stripe-api', 'fraud-detection'],
    clients: ['order-service'],
    revenueImpact: 2400000,
    activeIncidents: 0,
    sparklineData: [32, 30, 34, 31, 33, 32, 35, 31, 30, 33, 32, 34],
  },
  {
    id: 'user-service',
    name: 'User Service',
    status: 'healthy',
    description: 'User profile and preferences management',
    team: 'Identity',
    tier: 'T2',
    businessOwner: 'Marcus Johnson',
    slaTarget: 99.95,
    slaCurrent: 99.96,
    errorRate: 0.04,
    latencyP50: 15,
    latencyP99: 95,
    throughput: 12800,
    dependencies: ['user-db', 'redis-cache'],
    clients: ['api-gateway', 'auth-service'],
    revenueImpact: 600000,
    activeIncidents: 0,
    sparklineData: [12, 13, 11, 14, 12, 13, 15, 12, 11, 13, 14, 12],
  },
  {
    id: 'inventory-service',
    name: 'Inventory Service',
    status: 'critical',
    description: 'Real-time inventory tracking and stock management',
    team: 'Supply Chain',
    tier: 'T2',
    businessOwner: 'Rachel Torres',
    slaTarget: 99.9,
    slaCurrent: 98.5,
    errorRate: 1.5,
    latencyP50: 200,
    latencyP99: 1200,
    throughput: 4500,
    dependencies: ['inventory-db', 'warehouse-api', 'redis-cache'],
    clients: ['order-service'],
    revenueImpact: 950000,
    activeIncidents: 2,
    sparklineData: [45, 48, 52, 68, 95, 180, 320, 450, 380, 290, 250, 220],
  },
  {
    id: 'notification-service',
    name: 'Notification Service',
    status: 'healthy',
    description: 'Email, SMS, and push notification delivery',
    team: 'Platform',
    tier: 'T3',
    businessOwner: 'Sarah Chen',
    slaTarget: 99.9,
    slaCurrent: 99.92,
    errorRate: 0.08,
    latencyP50: 35,
    latencyP99: 180,
    throughput: 15600,
    dependencies: ['notification-db', 'email-provider', 'sms-provider'],
    clients: ['order-service', 'auth-service'],
    revenueImpact: 120000,
    activeIncidents: 0,
    sparklineData: [15, 16, 14, 17, 15, 16, 18, 15, 14, 16, 17, 15],
  },
  {
    id: 'fraud-detection',
    name: 'Fraud Detection',
    status: 'healthy',
    description: 'ML-powered fraud detection and prevention',
    team: 'Security',
    tier: 'T2',
    businessOwner: 'Alex Rivera',
    slaTarget: 99.95,
    slaCurrent: 99.97,
    errorRate: 0.03,
    latencyP50: 85,
    latencyP99: 350,
    throughput: 3200,
    dependencies: ['ml-model-store', 'fraud-db'],
    clients: ['payment-service'],
    revenueImpact: 450000,
    activeIncidents: 0,
    sparklineData: [85, 82, 88, 84, 86, 83, 87, 85, 82, 86, 84, 85],
  },
  {
    id: 'search-service',
    name: 'Search Service',
    status: 'healthy',
    description: 'Product and content search engine',
    team: 'Discovery',
    tier: 'T2',
    businessOwner: 'Emily Zhang',
    slaTarget: 99.9,
    slaCurrent: 99.94,
    errorRate: 0.06,
    latencyP50: 25,
    latencyP99: 150,
    throughput: 22000,
    dependencies: ['elasticsearch', 'redis-cache'],
    clients: ['api-gateway'],
    revenueImpact: 780000,
    activeIncidents: 0,
    sparklineData: [22, 24, 21, 23, 25, 22, 24, 26, 23, 21, 24, 22],
  },
  {
    id: 'analytics-service',
    name: 'Analytics Pipeline',
    status: 'healthy',
    description: 'Real-time business analytics and reporting',
    team: 'Data',
    tier: 'T3',
    businessOwner: 'James Wright',
    slaTarget: 99.5,
    slaCurrent: 99.8,
    errorRate: 0.2,
    latencyP50: 250,
    latencyP99: 800,
    throughput: 8500,
    dependencies: ['clickhouse', 'kafka', 'redis-cache'],
    clients: ['api-gateway'],
    revenueImpact: 200000,
    activeIncidents: 0,
    sparklineData: [85, 82, 88, 90, 85, 87, 92, 88, 84, 86, 90, 87],
  },
];

export const incidents: Incident[] = [
  {
    id: 'INC-2847',
    title: 'Inventory service degradation causing order failures',
    status: 'active',
    severity: 'critical',
    startedAt: '2026-04-03T08:23:00Z',
    affectedServices: ['inventory-service', 'order-service'],
    businessImpact: 'Order processing delayed — 12% of checkout attempts failing',
    revenueAtRisk: 185000,
    clientsAffected: 3420,
    correlationLayer: 'deterministic',
    confidenceScore: 92,
    rootCause: 'Inventory database connection pool exhaustion due to slow query on stock_levels table',
    timeline: [
      {
        timestamp: '2026-04-03T08:23:00Z',
        type: 'alert',
        description: 'Inventory service error rate exceeded 1% threshold',
        source: 'Grafana Alerting',
      },
      {
        timestamp: '2026-04-03T08:23:15Z',
        type: 'alert',
        description: 'Order service timeout rate increasing',
        source: 'Prometheus',
      },
      {
        timestamp: '2026-04-03T08:23:30Z',
        type: 'correlation',
        description: 'Events deduplicated: 47 alerts → 1 grouped incident',
        source: 'Correlation Engine',
        layer: 'direct',
      },
      {
        timestamp: '2026-04-03T08:24:00Z',
        type: 'hypothesis',
        description: 'AI hypothesis: Database connection pool exhaustion on inventory-db',
        source: 'RCA Engine',
        layer: 'statistical',
      },
      {
        timestamp: '2026-04-03T08:25:00Z',
        type: 'correlation',
        description: 'Deterministic link confirmed: inventory-service → inventory-db share hostname label',
        source: 'Correlation Engine',
        layer: 'deterministic',
      },
      {
        timestamp: '2026-04-03T08:26:30Z',
        type: 'action',
        description: 'Grafana Drilldown confirms: connection pool at 100%, slow query identified',
        source: 'Grafana Investigation',
        layer: 'direct',
      },
    ],
    rcaHypotheses: [
      {
        id: 'hyp-1',
        description: 'Database connection pool exhaustion on inventory-db due to slow query on stock_levels table',
        confidence: 92,
        layer: 'deterministic',
        evidence: [
          'Connection pool utilization at 100% (normally 35%)',
          'Query execution time for stock_levels increased from 5ms to 3200ms',
          'Shared hostname label links inventory-service alerts to inventory-db metrics',
          'Temporal correlation: latency spike started 2 minutes before alert threshold breach',
        ],
        status: 'confirmed',
      },
      {
        id: 'hyp-2',
        description: 'Network partition between inventory-service and database cluster',
        confidence: 23,
        layer: 'statistical',
        evidence: [
          'Similar pattern observed in past network incidents',
          'No direct network metric anomaly detected',
        ],
        status: 'rejected',
      },
      {
        id: 'hyp-3',
        description: 'Upstream traffic spike from flash sale causing resource contention',
        confidence: 45,
        layer: 'statistical',
        evidence: [
          'Traffic increased 40% in last hour',
          'However, traffic levels within normal flash sale parameters',
        ],
        status: 'rejected',
      },
    ],
  },
  {
    id: 'INC-2846',
    title: 'Elevated latency on API Gateway',
    status: 'resolved',
    severity: 'medium',
    startedAt: '2026-04-03T06:15:00Z',
    resolvedAt: '2026-04-03T06:52:00Z',
    affectedServices: ['api-gateway'],
    businessImpact: 'API response times increased 2x — no functional impact',
    revenueAtRisk: 0,
    clientsAffected: 0,
    correlationLayer: 'direct',
    confidenceScore: 98,
    rootCause: 'CDN cache invalidation triggered by deployment',
    timeline: [
      {
        timestamp: '2026-04-03T06:15:00Z',
        type: 'alert',
        description: 'API Gateway P99 latency exceeded 200ms threshold',
        source: 'Prometheus',
      },
      {
        timestamp: '2026-04-03T06:16:00Z',
        type: 'correlation',
        description: 'Direct reference: Deployment event trace ID matches latency spike window',
        source: 'Tempo',
        layer: 'direct',
      },
      {
        timestamp: '2026-04-03T06:52:00Z',
        type: 'resolved',
        description: 'Cache re-warmed, latency returned to normal',
        source: 'Grafana',
      },
    ],
    rcaHypotheses: [
      {
        id: 'hyp-4',
        description: 'CDN cache invalidation triggered by v2.14.3 deployment',
        confidence: 98,
        layer: 'direct',
        evidence: [
          'Deployment trace ID abc-123 directly linked to cache purge event',
          'Latency spike perfectly aligns with deployment window',
          'Cache hit ratio dropped from 94% to 12% at deployment time',
        ],
        status: 'confirmed',
      },
    ],
  },
  {
    id: 'INC-2840',
    title: 'Core network switch failure — multi-service outage',
    status: 'resolved',
    severity: 'critical',
    startedAt: '2026-04-01T14:30:00Z',
    resolvedAt: '2026-04-01T15:40:00Z',
    affectedServices: ['api-gateway', 'order-service', 'payment-service', 'user-service', 'inventory-service'],
    businessImpact: 'Complete service outage for 70 minutes — all transactions blocked',
    revenueAtRisk: 520000,
    clientsAffected: 45000,
    correlationLayer: 'statistical',
    confidenceScore: 87,
    rootCause: 'Core switch 7 hardware failure in primary datacenter',
    timeline: [
      {
        timestamp: '2026-04-01T14:30:00Z',
        type: 'alert',
        description: '1000+ alerts generated across all monitoring systems',
        source: 'Event Management',
      },
      {
        timestamp: '2026-04-01T14:30:30Z',
        type: 'correlation',
        description: 'Alerts deduplicated: 1047 alerts → 1 grouped incident',
        source: 'Correlation Engine',
        layer: 'direct',
      },
      {
        timestamp: '2026-04-01T14:32:00Z',
        type: 'hypothesis',
        description: 'AI correlates: Network layer failure on core infrastructure',
        source: 'RCA Engine',
        layer: 'statistical',
      },
      {
        timestamp: '2026-04-01T14:35:00Z',
        type: 'correlation',
        description: 'Trace patterns confirm: all traces fail at network timeout',
        source: 'Grafana Drilldown',
        layer: 'deterministic',
      },
      {
        timestamp: '2026-04-01T14:37:00Z',
        type: 'hypothesis',
        description: 'Likely cause: Core switch 7 (topology + event timing)',
        source: 'RCA Engine',
        layer: 'statistical',
      },
      {
        timestamp: '2026-04-01T14:40:00Z',
        type: 'action',
        description: 'Network team notified with specific asset ID',
        source: 'ITSM',
      },
      {
        timestamp: '2026-04-01T15:40:00Z',
        type: 'resolved',
        description: 'Core switch replaced, traffic failover complete',
        source: 'Network Ops',
      },
    ],
    rcaHypotheses: [
      {
        id: 'hyp-5',
        description: 'Core switch 7 hardware failure in primary datacenter',
        confidence: 87,
        layer: 'statistical',
        evidence: [
          'All affected services share topology path through switch 7',
          'SNMP traps stopped from switch 7 at incident start time',
          'Similar failure signature to historical network incidents',
          'Event timing analysis: cascade pattern matches network-origin failure',
        ],
        status: 'confirmed',
      },
    ],
  },
];

export const businessCapabilities: BusinessCapability[] = [
  {
    id: 'online-commerce',
    name: 'Online Commerce',
    description: 'End-to-end digital commerce experience from browsing to checkout',
    owner: 'Lisa Park',
    services: ['api-gateway', 'order-service', 'payment-service', 'inventory-service', 'search-service'],
    status: 'degraded',
    revenueContribution: 4200000,
    kpis: [
      { name: 'Conversion Rate', value: 3.2, target: 3.5, unit: '%', trend: 'down', sparkline: [3.5, 3.4, 3.6, 3.5, 3.3, 3.2, 3.1, 3.2, 3.0, 3.1, 3.2, 3.2] },
      { name: 'Cart Abandonment', value: 68, target: 60, unit: '%', trend: 'up', sparkline: [62, 61, 63, 64, 65, 66, 67, 68, 67, 68, 69, 68] },
      { name: 'Checkout Success', value: 88, target: 95, unit: '%', trend: 'down', sparkline: [95, 94, 95, 93, 91, 89, 87, 86, 87, 88, 88, 88] },
      { name: 'Avg. Order Value', value: 127, target: 120, unit: '$', trend: 'stable', sparkline: [125, 128, 124, 130, 126, 127, 129, 125, 128, 126, 127, 127] },
    ],
    clientRequirements: [
      {
        id: 'cr-1',
        name: 'Checkout Availability',
        description: 'Checkout flow must be available 99.95% of the time',
        priority: 'critical',
        slaTarget: 99.95,
        slaCurrent: 99.82,
        status: 'breached',
        linkedServices: ['order-service', 'payment-service', 'inventory-service'],
      },
      {
        id: 'cr-2',
        name: 'Payment Processing Time',
        description: 'Payments must complete within 3 seconds',
        priority: 'high',
        slaTarget: 99.9,
        slaCurrent: 99.98,
        status: 'met',
        linkedServices: ['payment-service'],
      },
      {
        id: 'cr-3',
        name: 'Search Response Time',
        description: 'Search results must return within 500ms',
        priority: 'medium',
        slaTarget: 99.5,
        slaCurrent: 99.94,
        status: 'met',
        linkedServices: ['search-service'],
      },
    ],
  },
  {
    id: 'identity-access',
    name: 'Identity & Access',
    description: 'User authentication, authorization, and profile management',
    owner: 'Marcus Johnson',
    services: ['auth-service', 'user-service'],
    status: 'healthy',
    revenueContribution: 0,
    kpis: [
      { name: 'Auth Success Rate', value: 99.8, target: 99.5, unit: '%', trend: 'stable', sparkline: [99.7, 99.8, 99.9, 99.7, 99.8, 99.8, 99.9, 99.8, 99.7, 99.8, 99.9, 99.8] },
      { name: 'Avg Login Time', value: 1.2, target: 2.0, unit: 's', trend: 'stable', sparkline: [1.3, 1.2, 1.1, 1.2, 1.3, 1.2, 1.1, 1.2, 1.2, 1.3, 1.2, 1.2] },
      { name: 'Token Refresh Rate', value: 15200, target: 20000, unit: '/min', trend: 'stable', sparkline: [15000, 15400, 14800, 15200, 15600, 15100, 15300, 15500, 15000, 15200, 15400, 15200] },
    ],
    clientRequirements: [
      {
        id: 'cr-4',
        name: 'Authentication Availability',
        description: 'Login and auth endpoints must be available 99.99% of the time',
        priority: 'critical',
        slaTarget: 99.99,
        slaCurrent: 99.99,
        status: 'met',
        linkedServices: ['auth-service'],
      },
    ],
  },
  {
    id: 'customer-engagement',
    name: 'Customer Engagement',
    description: 'Communication, notifications, and customer touchpoints',
    owner: 'Sarah Chen',
    services: ['notification-service', 'analytics-service'],
    status: 'healthy',
    revenueContribution: 320000,
    kpis: [
      { name: 'Notification Delivery', value: 99.2, target: 99.0, unit: '%', trend: 'stable', sparkline: [99.1, 99.3, 99.0, 99.2, 99.4, 99.1, 99.3, 99.2, 99.0, 99.3, 99.2, 99.2] },
      { name: 'Email Open Rate', value: 24.5, target: 22.0, unit: '%', trend: 'up', sparkline: [22.0, 22.5, 23.0, 23.2, 23.5, 23.8, 24.0, 24.2, 24.3, 24.4, 24.5, 24.5] },
      { name: 'Engagement Score', value: 72, target: 70, unit: '/100', trend: 'up', sparkline: [68, 69, 70, 70, 71, 71, 72, 72, 72, 73, 72, 72] },
    ],
    clientRequirements: [
      {
        id: 'cr-5',
        name: 'Notification Latency',
        description: 'Critical notifications must be delivered within 30 seconds',
        priority: 'high',
        slaTarget: 99.0,
        slaCurrent: 99.2,
        status: 'met',
        linkedServices: ['notification-service'],
      },
    ],
  },
  {
    id: 'security-compliance',
    name: 'Security & Compliance',
    description: 'Fraud detection, security monitoring, and regulatory compliance',
    owner: 'Alex Rivera',
    services: ['fraud-detection'],
    status: 'healthy',
    revenueContribution: 0,
    kpis: [
      { name: 'Fraud Detection Rate', value: 97.8, target: 95.0, unit: '%', trend: 'up', sparkline: [96.0, 96.2, 96.5, 96.8, 97.0, 97.2, 97.4, 97.5, 97.6, 97.7, 97.8, 97.8] },
      { name: 'False Positive Rate', value: 2.1, target: 5.0, unit: '%', trend: 'down', sparkline: [3.5, 3.2, 3.0, 2.8, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.1, 2.1] },
      { name: 'Scan Latency', value: 85, target: 200, unit: 'ms', trend: 'stable', sparkline: [88, 85, 82, 86, 84, 87, 85, 83, 86, 84, 85, 85] },
    ],
    clientRequirements: [
      {
        id: 'cr-6',
        name: 'Fraud Scan Coverage',
        description: '100% of transactions must pass fraud detection',
        priority: 'critical',
        slaTarget: 100,
        slaCurrent: 100,
        status: 'met',
        linkedServices: ['fraud-detection'],
      },
    ],
  },
];

export const dependencyNodes: DependencyNode[] = [
  { id: 'web-app', name: 'Web App', type: 'external', status: 'healthy', x: 80, y: 50, tier: 'T1' },
  { id: 'mobile-app', name: 'Mobile App', type: 'external', status: 'healthy', x: 80, y: 150, tier: 'T1' },
  { id: 'partner-api', name: 'Partner API', type: 'external', status: 'healthy', x: 80, y: 250, tier: 'T2' },
  { id: 'api-gateway', name: 'API Gateway', type: 'gateway', status: 'healthy', x: 280, y: 150, tier: 'T1' },
  { id: 'auth-service', name: 'Auth Service', type: 'service', status: 'healthy', x: 480, y: 50, tier: 'T1' },
  { id: 'user-service', name: 'User Service', type: 'service', status: 'healthy', x: 480, y: 150, tier: 'T2' },
  { id: 'order-service', name: 'Order Service', type: 'service', status: 'degraded', x: 480, y: 250, tier: 'T1' },
  { id: 'payment-service', name: 'Payment Service', type: 'service', status: 'healthy', x: 480, y: 350, tier: 'T1' },
  { id: 'search-service', name: 'Search Service', type: 'service', status: 'healthy', x: 480, y: 450, tier: 'T2' },
  { id: 'inventory-service', name: 'Inventory', type: 'service', status: 'critical', x: 680, y: 250, tier: 'T2' },
  { id: 'notification-service', name: 'Notifications', type: 'service', status: 'healthy', x: 680, y: 350, tier: 'T3' },
  { id: 'fraud-detection', name: 'Fraud Detection', type: 'service', status: 'healthy', x: 680, y: 450, tier: 'T2' },
  { id: 'user-db', name: 'User DB', type: 'database', status: 'healthy', x: 680, y: 50, tier: 'T1' },
  { id: 'order-db', name: 'Order DB', type: 'database', status: 'healthy', x: 680, y: 150, tier: 'T1' },
  { id: 'inventory-db', name: 'Inventory DB', type: 'database', status: 'critical', x: 880, y: 250, tier: 'T2' },
  { id: 'redis-cache', name: 'Redis Cache', type: 'database', status: 'healthy', x: 880, y: 100, tier: 'T2' },
  { id: 'elasticsearch', name: 'Elasticsearch', type: 'database', status: 'healthy', x: 680, y: 530, tier: 'T2' },
  { id: 'stripe-api', name: 'Stripe API', type: 'external', status: 'healthy', x: 680, y: 630, tier: 'T1' },
  { id: 'kafka', name: 'Kafka', type: 'queue', status: 'healthy', x: 880, y: 400, tier: 'T2' },
];

export const dependencyEdges: DependencyEdge[] = [
  { source: 'web-app', target: 'api-gateway', latency: 12, errorRate: 0.01, throughput: 25000, status: 'healthy' },
  { source: 'mobile-app', target: 'api-gateway', latency: 18, errorRate: 0.02, throughput: 15000, status: 'healthy' },
  { source: 'partner-api', target: 'api-gateway', latency: 25, errorRate: 0.01, throughput: 5200, status: 'healthy' },
  { source: 'api-gateway', target: 'auth-service', latency: 8, errorRate: 0.01, throughput: 32100, status: 'healthy' },
  { source: 'api-gateway', target: 'user-service', latency: 15, errorRate: 0.04, throughput: 12800, status: 'healthy' },
  { source: 'api-gateway', target: 'order-service', latency: 45, errorRate: 0.18, throughput: 8900, status: 'degraded' },
  { source: 'api-gateway', target: 'payment-service', latency: 120, errorRate: 0.02, throughput: 3200, status: 'healthy' },
  { source: 'api-gateway', target: 'search-service', latency: 25, errorRate: 0.06, throughput: 22000, status: 'healthy' },
  { source: 'auth-service', target: 'user-db', latency: 3, errorRate: 0.0, throughput: 32100, status: 'healthy' },
  { source: 'auth-service', target: 'redis-cache', latency: 1, errorRate: 0.0, throughput: 45000, status: 'healthy' },
  { source: 'user-service', target: 'user-db', latency: 4, errorRate: 0.0, throughput: 12800, status: 'healthy' },
  { source: 'user-service', target: 'redis-cache', latency: 1, errorRate: 0.0, throughput: 8000, status: 'healthy' },
  { source: 'order-service', target: 'order-db', latency: 5, errorRate: 0.01, throughput: 8900, status: 'healthy' },
  { source: 'order-service', target: 'inventory-service', latency: 200, errorRate: 1.5, throughput: 4500, status: 'critical' },
  { source: 'order-service', target: 'payment-service', latency: 120, errorRate: 0.02, throughput: 3200, status: 'healthy' },
  { source: 'order-service', target: 'notification-service', latency: 35, errorRate: 0.08, throughput: 8900, status: 'healthy' },
  { source: 'inventory-service', target: 'inventory-db', latency: 3200, errorRate: 5.0, throughput: 4500, status: 'critical' },
  { source: 'inventory-service', target: 'redis-cache', latency: 1, errorRate: 0.0, throughput: 12000, status: 'healthy' },
  { source: 'payment-service', target: 'stripe-api', latency: 350, errorRate: 0.01, throughput: 3200, status: 'healthy' },
  { source: 'payment-service', target: 'fraud-detection', latency: 85, errorRate: 0.03, throughput: 3200, status: 'healthy' },
  { source: 'search-service', target: 'elasticsearch', latency: 15, errorRate: 0.02, throughput: 22000, status: 'healthy' },
  { source: 'search-service', target: 'redis-cache', latency: 1, errorRate: 0.0, throughput: 15000, status: 'healthy' },
];

export const telemetrySources: TelemetrySource[] = [
  { name: 'Prometheus / Grafana', type: 'grafana', hostnameField: 'instance', serviceField: 'job', environmentField: 'env', status: 'connected', eventsPerSecond: 48500 },
  { name: 'Icinga Monitoring', type: 'monitoring', hostnameField: 'host_name', serviceField: 'check_command', environmentField: '_environment', status: 'connected', eventsPerSecond: 12300 },
  { name: 'Storage Appliance', type: 'appliance', hostnameField: 'storage_array', serviceField: 'N/A', environmentField: 'datacenter', status: 'connected', eventsPerSecond: 2100 },
  { name: 'Event Management', type: 'ems', hostnameField: 'hostname', serviceField: 'service', environmentField: 'environment', status: 'connected', eventsPerSecond: 8900 },
];

export const overviewStats = {
  totalServices: 10,
  healthyServices: 7,
  degradedServices: 2,
  criticalServices: 1,
  activeIncidents: 1,
  mttr: 37,
  mttd: 2.5,
  totalAlerts24h: 247,
  suppressedAlerts: 189,
  correlatedEvents: 1847,
  avgConfidenceScore: 89,
  revenueAtRisk: 185000,
  slaCompliance: 96.4,
  telemetryEventsPerSec: 71800,
};
