import type { Plugin } from './types';

export const defaultPlugins: Plugin[] = [
  // ─── Integrations ────────────────────────────────────────────
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Connect GitLab repositories, view pipelines, merge requests, and deployment status.',
    longDescription: `Integrate your GitLab instance to bring repository data, CI/CD pipelines, and merge request activity directly into Obbu. Track deployment frequency, lead time for changes, and correlate code changes with service health.

**Features:**
- View pipeline status across projects
- Track merge request activity and review cycles
- Correlate deployments with incident timelines
- Monitor GitLab Runner health
- Webhook support for real-time updates`,
    category: 'integration',
    icon: 'GitBranch',
    version: '2.4.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['git', 'ci/cd', 'source-control', 'pipelines'],
    featured: true,
    installCount: 2840,
    lastUpdated: '2026-03-28',
    configFields: [
      { key: 'instanceUrl', label: 'GitLab Instance URL', type: 'url', placeholder: 'https://gitlab.example.com', required: true, group: 'Connection' },
      { key: 'accessToken', label: 'Personal Access Token', type: 'password', description: 'Token with api and read_repository scopes', required: true, group: 'Connection' },
      { key: 'projects', label: 'Projects', type: 'textarea', placeholder: 'group/project-name (one per line)', description: 'GitLab projects to track. Leave empty for all accessible projects.', group: 'Scope' },
      { key: 'syncPipelines', label: 'Sync Pipelines', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'syncMergeRequests', label: 'Sync Merge Requests', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'syncDeployments', label: 'Sync Deployments', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'pollInterval', label: 'Poll Interval', type: 'select', defaultValue: '60', options: [{ label: '30 seconds', value: '30' }, { label: '1 minute', value: '60' }, { label: '5 minutes', value: '300' }], group: 'Advanced' },
    ],
    config: {},
    webhooks: [
      { id: 'gl-push', name: 'Push Events', direction: 'inbound', events: ['push', 'tag_push'], active: false },
      { id: 'gl-pipeline', name: 'Pipeline Events', direction: 'inbound', events: ['pipeline', 'job'], active: false },
      { id: 'gl-mr', name: 'Merge Request Events', direction: 'inbound', events: ['merge_request'], active: false },
    ],
    widgets: [
      { id: 'gl-pipelines', name: 'Pipeline Status', description: 'Live CI/CD pipeline status across projects', defaultSize: 'md' },
      { id: 'gl-mrs', name: 'Merge Requests', description: 'Open MRs with review status and age', defaultSize: 'md' },
      { id: 'gl-deployments', name: 'Deployment Feed', description: 'Recent deployments with environment info', defaultSize: 'sm' },
    ],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Connect GitHub repositories, track pull requests, Actions workflows, and Dependabot alerts.',
    longDescription: `Bring GitHub data into Obbu for full visibility across your development lifecycle. Track PR velocity, CI/CD health via GitHub Actions, and security posture through Dependabot alerts.

**Features:**
- Pull request tracking with review metrics
- GitHub Actions workflow monitoring
- Dependabot vulnerability alerts
- Release tracking and changelog generation
- Webhook support for real-time updates`,
    category: 'integration',
    icon: 'Github',
    version: '3.1.0',
    author: 'Obbu Core',
    status: 'enabled',
    tags: ['git', 'ci/cd', 'source-control', 'security'],
    featured: true,
    installCount: 4120,
    lastUpdated: '2026-04-01',
    configFields: [
      { key: 'token', label: 'Personal Access Token', type: 'password', description: 'Fine-grained PAT with repo and actions scopes', required: true, group: 'Connection' },
      { key: 'organization', label: 'Organization', type: 'text', placeholder: 'my-org', group: 'Scope' },
      { key: 'repositories', label: 'Repositories', type: 'textarea', placeholder: 'owner/repo (one per line)', description: 'Leave empty for all org repos', group: 'Scope' },
      { key: 'syncActions', label: 'Sync GitHub Actions', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'syncDependabot', label: 'Sync Dependabot Alerts', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'syncPRs', label: 'Sync Pull Requests', type: 'boolean', defaultValue: true, group: 'Features' },
    ],
    config: { token: '••••••••', organization: 'acme-corp', syncActions: true, syncDependabot: true, syncPRs: true },
    webhooks: [
      { id: 'gh-push', name: 'Push Events', direction: 'inbound', events: ['push'], active: true },
      { id: 'gh-pr', name: 'Pull Request Events', direction: 'inbound', events: ['pull_request', 'pull_request_review'], active: true },
      { id: 'gh-actions', name: 'Workflow Events', direction: 'inbound', events: ['workflow_run', 'workflow_job'], active: true },
    ],
    widgets: [
      { id: 'gh-actions', name: 'GitHub Actions', description: 'Workflow run status and duration trends', defaultSize: 'md' },
      { id: 'gh-prs', name: 'Pull Requests', description: 'Open PRs with review status and CI checks', defaultSize: 'md' },
      { id: 'gh-security', name: 'Security Alerts', description: 'Dependabot and code scanning alerts', defaultSize: 'sm' },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send alerts, incident updates, and RCA summaries to Slack channels.',
    category: 'integration',
    icon: 'MessageSquare',
    version: '1.8.0',
    author: 'Obbu Core',
    status: 'enabled',
    tags: ['notifications', 'messaging', 'alerts'],
    installCount: 3650,
    lastUpdated: '2026-03-15',
    configFields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'url', placeholder: 'https://hooks.slack.com/services/...', required: true, group: 'Connection' },
      { key: 'botToken', label: 'Bot Token', type: 'password', description: 'For interactive features (optional)', group: 'Connection' },
      { key: 'defaultChannel', label: 'Default Channel', type: 'text', placeholder: '#incidents', group: 'Routing' },
      { key: 'criticalChannel', label: 'Critical Alerts Channel', type: 'text', placeholder: '#critical-alerts', group: 'Routing' },
      { key: 'notifyOnIncident', label: 'Notify on New Incidents', type: 'boolean', defaultValue: true, group: 'Events' },
      { key: 'notifyOnRCA', label: 'Notify on RCA Completion', type: 'boolean', defaultValue: true, group: 'Events' },
      { key: 'notifyOnSLABreach', label: 'Notify on SLA Breach', type: 'boolean', defaultValue: true, group: 'Events' },
      { key: 'includeConfidence', label: 'Include AI Confidence Score', type: 'boolean', defaultValue: true, description: 'Show RCA confidence score in notifications', group: 'Format' },
    ],
    config: { webhookUrl: 'https://hooks.slack.com/services/T00/B00/xxx', defaultChannel: '#incidents', notifyOnIncident: true, notifyOnRCA: true, notifyOnSLABreach: true, includeConfidence: true },
    webhooks: [
      { id: 'slack-incident', name: 'Incident Notifications', direction: 'outbound', url: 'https://hooks.slack.com/services/...', events: ['incident.created', 'incident.resolved'], active: true },
      { id: 'slack-rca', name: 'RCA Notifications', direction: 'outbound', url: 'https://hooks.slack.com/services/...', events: ['rca.completed'], active: true },
    ],
    config: { webhookUrl: 'https://hooks.slack.com/services/T00/B00/xxx', defaultChannel: '#incidents', notifyOnIncident: true, notifyOnRCA: true, notifyOnSLABreach: true },
    widgets: [
      { id: 'slack-feed', name: 'Slack Activity', description: 'Recent Slack notifications sent by Obbu', defaultSize: 'sm' },
    ],
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    description: 'Bi-directional incident sync, on-call schedules, and escalation policy visibility.',
    category: 'integration',
    icon: 'Siren',
    version: '2.0.1',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['incidents', 'on-call', 'escalation', 'itsm'],
    featured: true,
    installCount: 1920,
    lastUpdated: '2026-03-20',
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, group: 'Connection' },
      { key: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'mycompany', required: true, group: 'Connection' },
      { key: 'serviceMapping', label: 'Service Mapping', type: 'textarea', placeholder: 'obbu-service:pagerduty-service (one per line)', description: 'Map Obbu services to PagerDuty services', group: 'Mapping' },
      { key: 'syncDirection', label: 'Sync Direction', type: 'select', defaultValue: 'bidirectional', options: [{ label: 'Bidirectional', value: 'bidirectional' }, { label: 'Obbu → PagerDuty', value: 'outbound' }, { label: 'PagerDuty → Obbu', value: 'inbound' }], group: 'Sync' },
      { key: 'autoAcknowledge', label: 'Auto-acknowledge in PagerDuty', type: 'boolean', defaultValue: false, description: 'When Obbu marks an incident as investigating', group: 'Automation' },
      { key: 'enrichTickets', label: 'Enrich with RCA Data', type: 'boolean', defaultValue: true, description: 'Attach RCA hypotheses to PagerDuty incidents', group: 'Automation' },
    ],
    config: {},
    webhooks: [
      { id: 'pd-incident', name: 'PagerDuty Incidents', direction: 'inbound', events: ['incident.trigger', 'incident.acknowledge', 'incident.resolve'], active: false },
    ],
    widgets: [
      { id: 'pd-oncall', name: 'On-Call Schedule', description: 'Current on-call rotation and escalation chain', defaultSize: 'sm' },
      { id: 'pd-incidents', name: 'PagerDuty Incidents', description: 'Active PagerDuty incidents with priority', defaultSize: 'md' },
    ],
  },
  {
    id: 'servicenow',
    name: 'ServiceNow',
    description: 'Create and sync ITSM tickets enriched with RCA context and correlation data.',
    category: 'integration',
    icon: 'Ticket',
    version: '1.5.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['itsm', 'tickets', 'change-management'],
    installCount: 1250,
    lastUpdated: '2026-03-10',
    configFields: [
      { key: 'instanceUrl', label: 'Instance URL', type: 'url', placeholder: 'https://mycompany.service-now.com', required: true, group: 'Connection' },
      { key: 'username', label: 'Username', type: 'text', required: true, group: 'Connection' },
      { key: 'password', label: 'Password', type: 'password', required: true, group: 'Connection' },
      { key: 'autoCreate', label: 'Auto-create Tickets', type: 'boolean', defaultValue: false, description: 'Create tickets when AI confidence ≥ 85%', group: 'Automation' },
      { key: 'assignmentGroup', label: 'Default Assignment Group', type: 'text', group: 'Routing' },
      { key: 'includeRCA', label: 'Include RCA Hypotheses', type: 'boolean', defaultValue: true, group: 'Content' },
      { key: 'includeTimeline', label: 'Include Incident Timeline', type: 'boolean', defaultValue: true, group: 'Content' },
    ],
    config: {},
    widgets: [],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Link incidents to Jira issues, track post-mortem action items, and sync statuses.',
    category: 'integration',
    icon: 'SquareKanban',
    version: '1.3.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['project-management', 'tickets', 'tracking'],
    installCount: 2100,
    lastUpdated: '2026-03-22',
    configFields: [
      { key: 'instanceUrl', label: 'Jira Cloud URL', type: 'url', placeholder: 'https://mycompany.atlassian.net', required: true, group: 'Connection' },
      { key: 'email', label: 'Email', type: 'text', required: true, group: 'Connection' },
      { key: 'apiToken', label: 'API Token', type: 'password', required: true, group: 'Connection' },
      { key: 'project', label: 'Default Project Key', type: 'text', placeholder: 'OPS', group: 'Scope' },
      { key: 'issueType', label: 'Default Issue Type', type: 'select', defaultValue: 'Bug', options: [{ label: 'Bug', value: 'Bug' }, { label: 'Task', value: 'Task' }, { label: 'Incident', value: 'Incident' }], group: 'Defaults' },
    ],
    config: {},
    widgets: [
      { id: 'jira-board', name: 'Incident Board', description: 'Kanban view of incident-related Jira issues', defaultSize: 'lg' },
    ],
  },

  // ─── Data Sources ────────────────────────────────────────────
  {
    id: 'prometheus',
    name: 'Prometheus',
    description: 'Federate metrics from Prometheus instances for unified observability.',
    longDescription: `Connect one or more Prometheus instances to aggregate metrics into Obbu's unified data layer. Supports federation, remote read, and PromQL queries.

**Features:**
- Multi-cluster federation support
- Custom PromQL query widgets
- Alert rule sync
- Service discovery integration
- Metric cardinality monitoring`,
    category: 'data-source',
    icon: 'BarChart3',
    version: '3.0.0',
    author: 'Obbu Core',
    status: 'enabled',
    tags: ['metrics', 'monitoring', 'prometheus', 'federation'],
    featured: true,
    installCount: 3800,
    lastUpdated: '2026-04-02',
    configFields: [
      { key: 'endpoints', label: 'Prometheus Endpoints', type: 'textarea', placeholder: 'https://prometheus.cluster-1.internal:9090 (one per line)', required: true, group: 'Connection' },
      { key: 'bearerToken', label: 'Bearer Token', type: 'password', description: 'For authenticated endpoints', group: 'Connection' },
      { key: 'scrapeInterval', label: 'Scrape Interval', type: 'select', defaultValue: '15', options: [{ label: '15 seconds', value: '15' }, { label: '30 seconds', value: '30' }, { label: '1 minute', value: '60' }], group: 'Collection' },
      { key: 'federation', label: 'Enable Federation', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'cardinalityLimit', label: 'Cardinality Limit per Metric', type: 'number', defaultValue: 10000, description: 'Cap distinct label values to prevent explosion', group: 'Advanced' },
    ],
    config: { endpoints: 'https://prometheus.prod.internal:9090\nhttps://prometheus.staging.internal:9090', scrapeInterval: '15', federation: true, cardinalityLimit: 10000 },
    widgets: [
      { id: 'prom-query', name: 'PromQL Widget', description: 'Run custom PromQL queries and visualize results', defaultSize: 'md' },
      { id: 'prom-targets', name: 'Scrape Targets', description: 'Health status of all Prometheus scrape targets', defaultSize: 'sm' },
      { id: 'prom-cardinality', name: 'Cardinality Monitor', description: 'Track metric cardinality across instances', defaultSize: 'sm' },
    ],
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Embed Grafana dashboards and leverage Drilldown apps for RCA investigation.',
    category: 'data-source',
    icon: 'LayoutDashboard',
    version: '2.2.0',
    author: 'Obbu Core',
    status: 'enabled',
    tags: ['visualization', 'dashboards', 'drilldown'],
    installCount: 3200,
    lastUpdated: '2026-03-30',
    configFields: [
      { key: 'url', label: 'Grafana URL', type: 'url', placeholder: 'https://grafana.example.com', required: true, group: 'Connection' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, group: 'Connection' },
      { key: 'orgId', label: 'Organization ID', type: 'number', defaultValue: 1, group: 'Connection' },
      { key: 'embedDashboards', label: 'Dashboard UIDs to Embed', type: 'textarea', placeholder: 'dashboard-uid (one per line)', group: 'Dashboards' },
      { key: 'enableDrilldown', label: 'Enable Drilldown Integration', type: 'boolean', defaultValue: true, description: 'Use Grafana Drilldown for RCA hypothesis validation', group: 'Features' },
    ],
    config: { url: 'https://grafana.prod.internal', orgId: 1, enableDrilldown: true },
    widgets: [
      { id: 'grafana-embed', name: 'Embedded Dashboard', description: 'Embed any Grafana dashboard panel', defaultSize: 'lg' },
      { id: 'grafana-alerts', name: 'Grafana Alerts', description: 'Active Grafana alert rules and their states', defaultSize: 'sm' },
    ],
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch / OpenSearch',
    description: 'Aggregate and search logs from Elasticsearch or OpenSearch clusters.',
    category: 'data-source',
    icon: 'Search',
    version: '1.6.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['logs', 'search', 'aggregation'],
    installCount: 1800,
    lastUpdated: '2026-03-18',
    configFields: [
      { key: 'nodes', label: 'Cluster Nodes', type: 'textarea', placeholder: 'https://es-node-1:9200 (one per line)', required: true, group: 'Connection' },
      { key: 'username', label: 'Username', type: 'text', group: 'Connection' },
      { key: 'password', label: 'Password', type: 'password', group: 'Connection' },
      { key: 'indexPattern', label: 'Index Pattern', type: 'text', placeholder: 'logs-*', defaultValue: 'logs-*', group: 'Scope' },
      { key: 'timestampField', label: 'Timestamp Field', type: 'text', defaultValue: '@timestamp', group: 'Scope' },
    ],
    config: {},
    widgets: [
      { id: 'es-search', name: 'Log Search', description: 'Search and filter logs with KQL syntax', defaultSize: 'lg' },
      { id: 'es-volume', name: 'Log Volume', description: 'Log ingestion rate over time', defaultSize: 'sm' },
    ],
  },
  {
    id: 'otel-collector',
    name: 'OpenTelemetry Collector',
    description: 'Receive, process, and export telemetry data via OTel Collector pipelines.',
    category: 'data-source',
    icon: 'Radio',
    version: '1.2.0',
    author: 'Obbu Core',
    status: 'enabled',
    tags: ['opentelemetry', 'traces', 'metrics', 'logs', 'normalization'],
    installCount: 2400,
    lastUpdated: '2026-04-01',
    configFields: [
      { key: 'grpcEndpoint', label: 'gRPC Endpoint', type: 'url', placeholder: 'otel-collector:4317', required: true, group: 'Connection' },
      { key: 'httpEndpoint', label: 'HTTP Endpoint', type: 'url', placeholder: 'otel-collector:4318', group: 'Connection' },
      { key: 'enableFiltering', label: 'Enable Filter Processor', type: 'boolean', defaultValue: true, description: 'Filter irrelevant telemetry before aggregation', group: 'Processing' },
      { key: 'enableEnrichment', label: 'Enable Resource Enrichment', type: 'boolean', defaultValue: true, description: 'Enrich with CMDB/topology data', group: 'Processing' },
      { key: 'semanticConventions', label: 'Enforce Semantic Conventions', type: 'boolean', defaultValue: true, description: 'Normalize fields to OTel semantic conventions', group: 'Normalization' },
    ],
    config: { grpcEndpoint: 'otel-collector.monitoring:4317', enableFiltering: true, enableEnrichment: true, semanticConventions: true },
    widgets: [
      { id: 'otel-pipeline', name: 'Pipeline Health', description: 'OTel Collector pipeline throughput and errors', defaultSize: 'md' },
    ],
  },

  // ─── Widgets ─────────────────────────────────────────────────
  {
    id: 'health-check',
    name: 'Custom Health Checks',
    description: 'Monitor any HTTP endpoint with configurable checks, thresholds, and alerts.',
    category: 'widget',
    icon: 'HeartPulse',
    version: '1.4.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['monitoring', 'uptime', 'health'],
    installCount: 2100,
    lastUpdated: '2026-03-25',
    configFields: [
      { key: 'checks', label: 'Health Check Endpoints', type: 'textarea', placeholder: 'https://api.example.com/health (one per line)', required: true, group: 'Endpoints' },
      { key: 'interval', label: 'Check Interval', type: 'select', defaultValue: '30', options: [{ label: '15 seconds', value: '15' }, { label: '30 seconds', value: '30' }, { label: '1 minute', value: '60' }, { label: '5 minutes', value: '300' }], group: 'Schedule' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 5000, group: 'Schedule' },
      { key: 'alertOnFailure', label: 'Alert on Failure', type: 'boolean', defaultValue: true, group: 'Alerts' },
      { key: 'consecutiveFailures', label: 'Consecutive Failures Before Alert', type: 'number', defaultValue: 3, group: 'Alerts' },
    ],
    config: {},
    widgets: [
      { id: 'hc-grid', name: 'Health Check Grid', description: 'Grid of endpoint health with latency and uptime', defaultSize: 'md' },
      { id: 'hc-uptime', name: 'Uptime History', description: '30-day uptime history with incident markers', defaultSize: 'lg' },
    ],
  },
  {
    id: 'cicd-pipelines',
    name: 'CI/CD Pipeline Viewer',
    description: 'Unified view of build and deployment pipelines across all connected CI/CD systems.',
    category: 'widget',
    icon: 'Workflow',
    version: '1.1.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['ci/cd', 'builds', 'deployments'],
    installCount: 1650,
    lastUpdated: '2026-03-12',
    configFields: [
      { key: 'sources', label: 'Pipeline Sources', type: 'multiselect', options: [{ label: 'GitLab CI', value: 'gitlab' }, { label: 'GitHub Actions', value: 'github' }, { label: 'Jenkins', value: 'jenkins' }, { label: 'ArgoCD', value: 'argocd' }], group: 'Sources' },
      { key: 'showOnlyFailed', label: 'Show Only Failed Pipelines', type: 'boolean', defaultValue: false, group: 'Display' },
      { key: 'environments', label: 'Environments', type: 'multiselect', options: [{ label: 'Production', value: 'prod' }, { label: 'Staging', value: 'staging' }, { label: 'Development', value: 'dev' }], group: 'Scope' },
    ],
    config: {},
    widgets: [
      { id: 'cicd-status', name: 'Pipeline Status', description: 'Aggregated pipeline status across CI/CD systems', defaultSize: 'lg' },
      { id: 'cicd-frequency', name: 'Deploy Frequency', description: 'Deployment frequency DORA metric', defaultSize: 'sm' },
    ],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes Monitor',
    description: 'Monitor cluster health, pod status, resource utilization, and events.',
    category: 'widget',
    icon: 'Container',
    version: '2.0.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['kubernetes', 'containers', 'infrastructure', 'orchestration'],
    featured: true,
    installCount: 2950,
    lastUpdated: '2026-04-02',
    configFields: [
      { key: 'clusters', label: 'Cluster Configs', type: 'textarea', placeholder: 'cluster-name:https://k8s-api:6443 (one per line)', required: true, group: 'Connection' },
      { key: 'kubeconfig', label: 'Kubeconfig Path', type: 'text', placeholder: '/etc/obbu/kubeconfig', group: 'Connection' },
      { key: 'namespaces', label: 'Namespaces', type: 'textarea', placeholder: 'default (one per line, empty = all)', group: 'Scope' },
      { key: 'monitorPods', label: 'Monitor Pods', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'monitorNodes', label: 'Monitor Nodes', type: 'boolean', defaultValue: true, group: 'Features' },
      { key: 'monitorEvents', label: 'Collect Events', type: 'boolean', defaultValue: true, group: 'Features' },
    ],
    config: {},
    widgets: [
      { id: 'k8s-overview', name: 'Cluster Overview', description: 'Pod, node, and namespace health at a glance', defaultSize: 'lg' },
      { id: 'k8s-pods', name: 'Pod Status', description: 'Pod status with restart counts and resource usage', defaultSize: 'md' },
      { id: 'k8s-events', name: 'Cluster Events', description: 'Recent Kubernetes events with severity', defaultSize: 'sm' },
    ],
  },
  {
    id: 'webhook-manager',
    name: 'Webhook Manager',
    description: 'Configure inbound and outbound webhooks for custom integrations and automations.',
    category: 'widget',
    icon: 'Webhook',
    version: '1.0.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['webhooks', 'integration', 'automation'],
    installCount: 980,
    lastUpdated: '2026-03-08',
    configFields: [
      { key: 'secret', label: 'Webhook Secret', type: 'password', description: 'HMAC secret for validating inbound webhooks', group: 'Security' },
      { key: 'retryAttempts', label: 'Outbound Retry Attempts', type: 'number', defaultValue: 3, group: 'Reliability' },
      { key: 'retryDelay', label: 'Retry Delay (seconds)', type: 'number', defaultValue: 5, group: 'Reliability' },
    ],
    config: {},
    webhooks: [
      { id: 'wh-custom-1', name: 'Custom Inbound #1', direction: 'inbound', events: ['*'], active: false },
      { id: 'wh-custom-2', name: 'Custom Outbound #1', direction: 'outbound', url: '', events: ['incident.created'], active: false },
    ],
    widgets: [
      { id: 'wh-log', name: 'Webhook Activity', description: 'Recent webhook deliveries with status and payload', defaultSize: 'md' },
    ],
  },
  {
    id: 'sla-monitor',
    name: 'SLA Monitor',
    description: 'Define custom SLA objectives and track compliance with burn-rate alerting.',
    category: 'widget',
    icon: 'Target',
    version: '1.2.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['sla', 'slo', 'compliance', 'business'],
    installCount: 1400,
    lastUpdated: '2026-03-20',
    configFields: [
      { key: 'objectives', label: 'SLA Objectives', type: 'textarea', placeholder: 'service:metric:target (e.g., api-gateway:availability:99.95)', group: 'Objectives' },
      { key: 'window', label: 'Evaluation Window', type: 'select', defaultValue: '30d', options: [{ label: '7 days', value: '7d' }, { label: '30 days', value: '30d' }, { label: '90 days', value: '90d' }], group: 'Evaluation' },
      { key: 'burnRateAlert', label: 'Enable Burn Rate Alerting', type: 'boolean', defaultValue: true, description: 'Alert when error budget consumption rate exceeds threshold', group: 'Alerts' },
    ],
    config: {},
    widgets: [
      { id: 'sla-status', name: 'SLA Status', description: 'All SLA objectives with current compliance', defaultSize: 'md' },
      { id: 'sla-budget', name: 'Error Budget', description: 'Error budget remaining with burn rate', defaultSize: 'sm' },
    ],
  },

  // ─── Automations ─────────────────────────────────────────────
  {
    id: 'auto-remediation',
    name: 'Auto-Remediation',
    description: 'Define runbooks that execute automatically when RCA confidence exceeds threshold.',
    longDescription: `Automate incident response with configurable runbooks triggered by RCA hypotheses. Supports approval gates, dry-run mode, and audit logging.

**Safety:**
- Requires confidence ≥ 85% by default
- Shadow mode available for dry-run testing
- All actions are logged and auditable
- Manual approval gates for destructive actions`,
    category: 'automation',
    icon: 'Wand2',
    version: '0.9.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['automation', 'remediation', 'runbooks', 'ai'],
    installCount: 680,
    lastUpdated: '2026-03-28',
    configFields: [
      { key: 'minConfidence', label: 'Minimum Confidence for Auto-Action', type: 'number', defaultValue: 85, description: 'RCA confidence threshold (from paper: ≥ 85% for auto, 50-85% manual validation)', group: 'Thresholds' },
      { key: 'shadowMode', label: 'Shadow Mode', type: 'boolean', defaultValue: true, description: 'Log actions without executing (recommended for first 4-8 weeks)', group: 'Safety' },
      { key: 'requireApproval', label: 'Require Manual Approval', type: 'boolean', defaultValue: true, description: 'Prompt for approval before executing destructive actions', group: 'Safety' },
      { key: 'maxActionsPerHour', label: 'Max Actions Per Hour', type: 'number', defaultValue: 5, group: 'Rate Limits' },
    ],
    config: {},
    widgets: [
      { id: 'ar-actions', name: 'Remediation Log', description: 'Recent auto-remediation actions with outcomes', defaultSize: 'md' },
    ],
  },
  {
    id: 'alert-router',
    name: 'Alert Router',
    description: 'Route, deduplicate, and suppress alerts based on rules, schedules, and context.',
    category: 'automation',
    icon: 'Route',
    version: '1.3.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['alerts', 'routing', 'deduplication', 'suppression'],
    installCount: 1100,
    lastUpdated: '2026-03-15',
    configFields: [
      { key: 'deduplicationWindow', label: 'Dedup Window (seconds)', type: 'number', defaultValue: 300, group: 'Deduplication' },
      { key: 'groupByFields', label: 'Group By Fields', type: 'multiselect', options: [{ label: 'Service', value: 'service' }, { label: 'Host', value: 'host' }, { label: 'Environment', value: 'env' }, { label: 'Severity', value: 'severity' }], group: 'Grouping' },
      { key: 'suppressDuringMaintenance', label: 'Suppress During Maintenance', type: 'boolean', defaultValue: true, description: 'Blackout periods for planned maintenance', group: 'Suppression' },
      { key: 'maintenanceCalendar', label: 'Maintenance Calendar URL', type: 'url', placeholder: 'https://calendar.example.com/maintenance.ics', group: 'Suppression' },
    ],
    config: {},
    widgets: [
      { id: 'ar-stats', name: 'Alert Stats', description: 'Alert volume, dedup rate, and routing summary', defaultSize: 'sm' },
    ],
  },
  {
    id: 'report-generator',
    name: 'Report Generator',
    description: 'Generate scheduled PDF/HTML reports on service health, SLAs, and incident summaries.',
    category: 'automation',
    icon: 'FileBarChart',
    version: '1.0.0',
    author: 'Obbu Core',
    status: 'disabled',
    tags: ['reports', 'scheduling', 'pdf', 'executive'],
    installCount: 750,
    lastUpdated: '2026-03-05',
    configFields: [
      { key: 'schedule', label: 'Report Schedule', type: 'select', defaultValue: 'weekly', options: [{ label: 'Daily', value: 'daily' }, { label: 'Weekly', value: 'weekly' }, { label: 'Monthly', value: 'monthly' }], group: 'Schedule' },
      { key: 'format', label: 'Report Format', type: 'select', defaultValue: 'pdf', options: [{ label: 'PDF', value: 'pdf' }, { label: 'HTML', value: 'html' }, { label: 'Both', value: 'both' }], group: 'Format' },
      { key: 'recipients', label: 'Email Recipients', type: 'textarea', placeholder: 'email@example.com (one per line)', group: 'Delivery' },
      { key: 'sections', label: 'Report Sections', type: 'multiselect', options: [{ label: 'Service Health', value: 'health' }, { label: 'SLA Compliance', value: 'sla' }, { label: 'Incident Summary', value: 'incidents' }, { label: 'RCA Analysis', value: 'rca' }, { label: 'Business Impact', value: 'business' }], group: 'Content' },
    ],
    config: {},
    widgets: [],
  },
];
